ARG ALPINE_VERSION=3.18
FROM docker.io/alpine:${ALPINE_VERSION}

RUN apk add \
	alpine-sdk \
	linux-headers \
	confuse \
	confuse-dev \
	check \
	check-dev \
	gdb \
	curl \
	git \
	gcovr \
	bats \
	subunit \
	subunit-dev \
	py3-pygments
